spring.config.import=optional:file:.env[.properties],optional:file:payment-receipt-api/.env[.properties]
spring.application.name=${APP_NAME:payment-receipt}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/payment-receipt_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.ai.openai.api-key=${GROQ_API_KEY:${OPENAI_API_KEY:}}
spring.ai.openai.base-url=${GROQ_BASE_URL:https://api.groq.com/openai/v1}
spring.ai.openai.chat.model=${GROQ_MODEL:meta-llama/llama-4-scout-17b-16e-instruct}
spring.docker.compose.enabled=false
